### ISSUE TITLE
pointer-events

### ISSUE THREAD

**Issue by scottbarrow** [leastbad/radiolabel#1]
Thanks for the tool, this will be useful for debugging

I find the animation overlay a little obtrusive as it blocks pointer-events, would it be possible to add a `pointer-events: none` to the overlay so that elements can be interacted with during fade out? 
I guess this poses the challenge that the animation would need to be halted to allow the next event to occur if a subsequent reflex is triggered during a fade out of a previous reflex

**Comment by leastbad** [comment]
This was a great idea, Scott. I'm just adding it, now. (Sorry for the delay!)

Could you clarify what you mean in your last sentence? I'm not challenging the assertion, just trying to grok it because you're probably right.

The controller dynamically creates a new div (two, including the title) for each CableReady operation, before destroying it. They both occupy the same z-index but with absolute positioning, so multiple overlays should be able to coexist. Each will have their own animation timeline. Does this address your concern?

**Comment by scottbarrow** [comment]
ah gotcha, yes that does, thanks!
